### ISSUE TITLE
Parse XOR'd block data

### ISSUE THREAD

**Issue by bczhc** [sumopool/bitcoin-block-parser#2]
Thanks for the great and convenient library! During my parsing testnet experience, I encountered errors with this lib. After manually handling them, I found something wrong with the block files.

And finally.. The problem is, starting from Bitcoin-core 28, block data is XORed. The XOR mask is stored in `xor.dat`.

This is only enabled for the freshly generated blk files with newer Bitcoin-core versions. For the old blk files, `xor.dat` file is just `0000 0000 0000 0000`, which essentially is an XOR no-op.

See:

- https://bitcoin.stackexchange.com/questions/124686/unable-to-parse-blocks-from-blk-dat-for-testnet-3-and-4
- https://github.com/bitcoin/bitcoin/pull/28052

**Comment by sumopool** [comment]
Thanks for taking initiative to contribute!  I tested locally to confirm this works on bitcoin core 28.0
