### ISSUE TITLE
Severe memory leak when stdout gets locked and with `order_output` options

### ISSUE THREAD

**Issue by bczhc** [sumopool/bitcoin-block-parser#5]
Just found a very interesting case. The code below causes a severe memory leak.

```rust
use std::io::{stdin, stdout};
use bitcoin_block_parser::{BlockParser, DefaultParser, HeaderParser};
use bitcoin_block_parser::blocks::Options;

fn main() {
    let _a = stdout().lock();

    let options = Options::default().order_output();

    let headers = HeaderParser::parse("/mnt/nvme/bitcoin/bitcoind/blocks/blocks").unwrap();
    let headers = &headers[..250000];
    let parser=DefaultParser.parse_with_opts(&headers, options);

    for _x in parser {
    }
    println!("Done.");
    // this just prevents program from quitting.
    stdin().read_line(&mut String::new()).unwrap();
}

```

The program eats ~17GB of memory. If not constraining the header range, an OOM will occur. Also the code above hangs, that's, `Done` will never be printed out.

However, either disabling `order_output` or removing the `.lock()` on stdout makes the issue not happen.

**Comment by bczhc** [comment]
Found the cause. `println!` from a new thread triggers the deadlock.

https://github.com/sumopool/bitcoin-block-parser/blob/2ada3f5c9bbcfc00ba31e1326a11dbbfa4eb9f91/src/blocks.rs#L168

The line blocks, and the data just gets more and more in the channel.

**Comment by sumopool** [comment]
Yes, I just confirmed this...by merging your `log` change users can avoid this.
